apiVersion: v1
kind: Service
metadata:
  name: nodeapptest-docker     
spec:
  selector:
    deploymentconfig: nodeapptest-docker
    # IP WILL ASSIGN AUTOMATICALLY
  ports:
  - name: 8080-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8080         